# Generated by Django 5.2.1 on 2025-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 10 para 10%', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
