# Generated by Django 5.2.1 on 2025-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_solicitudproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
