# Generated by Django 5.2.3 on 2025-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='archivo_boleta',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
    ]
